spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME:library}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: WARN
    com.collabera.libraryapi: INFO

springdoc:
  swagger-ui:
    enabled: false
