name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        run: mvn -B verify

      - name: Coverage Summary
        if: always()
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            INSTR=$(grep -o 'instructionCoverage>[^<]*' target/site/jacoco/jacoco.xml | head -1 | sed 's/.*instructionCoverage>//' || true)
            BRANCH=$(grep -o 'branchCoverage>[^<]*' target/site/jacoco/jacoco.xml | head -1 | sed 's/.*branchCoverage>//' || true)
            echo "Instruction coverage: $INSTR" | tee -a $GITHUB_STEP_SUMMARY
            echo "Branch coverage: $BRANCH" | tee -a $GITHUB_STEP_SUMMARY
          else
            echo "No jacoco.xml found" | tee -a $GITHUB_STEP_SUMMARY
          fi

      - name: Upload JaCoCo XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml
          path: target/site/jacoco/jacoco.xml

      - name: Login to GHCR
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image (GHCR)
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          IMAGE: ghcr.io/${{ github.repository }}/library-api:sha-${{ github.sha }}
          IMAGE_SHORT: ghcr.io/${{ github.repository }}/library-api:latest
        run: |
          docker build -t "$IMAGE" -t "$IMAGE_SHORT" .
          docker push "$IMAGE"
          docker push "$IMAGE_SHORT"
